### PR TITLE
feat: Support syntax for vertex/edge property access

### PR DESCRIPTION
**Pull request by protodef**
If type of `var` in expression `(var).ind` is vertex/edge, transform it
to `(var).prop_map #> ARRAY[ind...]`.

`ind` is a series of following operations;
* `.key`
* `['key']`
* `[index]`

And also, it is possible to use this syntax on jsonb/json.

### CODE REVIEW

**Comment by htlim** [comment]
I tried to test in the traditional manner as follows.

htlim=# create (b:test1 '{"name":"test1"}') return (b).prop_map->>'name';
 ?column? 
----------
 
(1 row)

Incorrect results are displayed,
Is this intended results?

**Comment by protodef** [comment]
No. But the result is reproducible through the following example query.
`SELECT '{}'::jsonb #> '{prop_map}' ->> 'name';`
The expression in the above query yields the same result.
`(b)` does not have `'prop_map'` key in its properties and `#>` operator (`jsonb_extract_path()` function) returns NULL(different from `'null'::jsonb`) if it cannot resolve the given path.
And the behavior of `->>` operator is the same as `#>` operator.
Currently, it is not clear how to handle this properly.

**Comment by protodef** [comment]
I will leave a comment about [above issue](https://github.com/bitnine-oss/agens-graph/pull/41#issuecomment-238474443) if I find out a reasonable way to handle it.

Anyway, I'm going to add some functions to get id, prop_map from vertex/edge and fix regression tests due to 75c95d9.

**Comment by protodef** [comment]
It seems reasonable to return NULL when extracting non-existent element from properties with given path. Throwing an error in such ᅟa case looks inefficient when the running time of the query is long and it appears on the very last.

**Pull request merged**
