### PR TITLE
[WIP] Add binary in/out for graphid

### PR DESCRIPTION
**Pull request by johnberzy-bazinga**
Hello, 

This pull request adds binary in/out functions for the Graphid type. It addresses issue #115.
 
I was not sure how to add tests for this within the project, but I've tested both input and output manually by connecting via the Npgsql driver and using graphid as a parameter and return type for functions and queries. This id is sent/received as an 8 byte over the wire rather than breaking it apart into label + location id (2 + 8). I'm not sure if this is the right strategy. 

In pg_proc.h I'm not sure what all the columns mean. Please advise if I've got those wrong.

Thanks,
John

### CODE REVIEW

**Comment by johnberzy-bazinga** [comment]
Ok, I've updates the columns in pg_proc to refer to graphid. I think I got it right this time, but then again...

b7e

**Comment by protodef** [comment]
I've tried to make some regression tests for the pull request. When I run the statements below, the result value is not properly printed.

```
CREATE TABLE tmp (id graphid);
INSERT INTO tmp VALUES ('1.1'), ('2.2');
BEGIN;
DECLARE tmp_cur BINARY CURSOR FOR SELECT id FROM tmp;
FETCH NEXT FROM tmp_cur;
 id 
----
 
(1 row)

CLOSE CURSOR;
COMMIT;
```

**Comment by johnberzy-bazinga** [comment]
@protodef thanks for taking a look at the PR. It's not completely clear to me what the behavior should be. I've tested your example by returning an oid instead of graphid and it behaves the same (no output for the cell). Do you know offhand of a type that displays the desired behavior and I'll try to update the behaviour to mimic that. 

Thanks
John

**Comment by protodef** [comment]
I used `COPY TO` and `COPY FROM` to test binary in/out for graphid and found out that they works. But I don't know how to add this test to the existing regression tests. So, I've applied the pull request first.

Thanks for the pull request.

**Comment by johnberzy-bazinga** [comment]
@protodef Thanks! Have a great weekend!

**Pull request closed without merging**
